# Generated by Django 2.1.2 on 2018-10-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField(unique=True, verbose_name='DNI')),
                ('Name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Last_Name', models.CharField(max_length=20, verbose_name='Apellido')),
                ('Email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('Password', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
