# Generated by Django 2.1.2 on 2018-10-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del curso')),
                ('duration', models.FloatField(verbose_name='Duracion de la pelicula')),
                ('description', models.TextField(max_length=300, verbose_name='Descripcion de la pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido')),
            ],
        ),
        migrations.CreateModel(
            name='User_has_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=10, verbose_name='Precio de la entrada')),
                ('Movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_has_Movie', to='user.Movie')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_has_Movie', to='user.User')),
            ],
        ),
    ]
