# Generated by Django 2.1.2 on 2018-10-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181006_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estreno de la pelicula'),
        ),
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='movies', verbose_name='Foto de la pelicula'),
        ),
        migrations.AddField(
            model_name='user_has_movie',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha de la compra'),
        ),
    ]
