# Generated by Django 2.1.2 on 2018-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181007_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_has_movie',
            name='place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Lugar de la función'),
        ),
        migrations.AddField(
            model_name='user_has_movie',
            name='room_cinema',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sala de la función'),
        ),
        migrations.AddField(
            model_name='user_has_movie',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora de la función'),
        ),
    ]
