# Generated by Django 2.1.2 on 2018-10-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181011_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='clients',
            field=models.ManyToManyField(through='user.User_has_Movie', to='user.User'),
        ),
    ]
