# Generated by Django 2.1.2 on 2018-10-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_movie_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='DNI',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
