# Generated by Django 2.1.2 on 2018-10-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181016_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_has_movie',
            name='Movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_has_Movie', to='user.Movie'),
        ),
        migrations.AlterField(
            model_name='user_has_movie',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_has_Movie', to='user.User'),
        ),
    ]
